### ISSUE TITLE
사이트에 MediaQuery 적용하기

### ISSUE THREAD

**Issue by llighter** [llighter/Material-Web#2]
반응형 웹 디자인 기본 사항
https://developers.google.com/web/fundamentals/design-and-ux/responsive/

Layout Grid
https://material.io/develop/web/components/layout-grid/#margins-and-gutters

**Comment by llighter** [comment]
일정이상 넓이가 넓어지는 경우 미디어쿼리를 활용하여 크기가 늘어나지 않도록 한다.
관련 예제는 [유동형(Mostly Fluid)](https://developers.google.com/web/fundamentals/design-and-ux/responsive/patterns?hl=ko) 에서 확인할 수 있다.
```css
@media (min-width: 800px) {
  .container {
    width: 800px;
    margin-left: auto;
    margin-right: auto;
  }
}
```

여기에 [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)의 justify-content를 속성을 이용해서 중앙으로 정렬하면 얼추 원하는 바를 얻을 수 있을 것 같다.

**Comment by llighter** [comment]
[그리드 행동방식](https://material.io/design/layout/responsive-layout-grid.html#grid-behavior)을 보면 내가 원하는 건 Fixed Grid 방식이다.

**Comment by llighter** [comment]
다른 예제에서 보면 마찬가지로 진행한다.
https://coder-coder.com/build-flexbox-website-layout/
```css
.flex-container {
    @media screen and (min-width: 640px){
        display: flex;
    }    
}
```
처음 레이아웃을 짤 때 위 예제처럼 아무것도 없는 기본배치를 해놓은 다음에 스타일을 적용시켜 나가는 방식을 써보자.

오컴의 면도날을 기억하자.
여러가지 방법이 있다면 단순한 것이 가장 효율적이다.

[wev.dev](https://web.dev/) 소스를 참고하는 것은 각 컴포넌트 단위일 때 참고하도록 하자.
